version: '3.1'
services:
  expression-eval:
    build: ../expression-eval
    image: oli/expression-eval
    container_name: expression-eval
    ports:
      - "8000:8000"
    networks:
      - service-tier
  mysql-keycloak:
    build: ./mysql-keycloak
    container_name: oli-mysql-keycloak
    env_file:
      - ./keycloak-mysql/keycloak.envs
    volumes:
      - /oli/databases/keycloak:/var/lib/mysql
#      - keycloak-db:/var/lib/mysql
    networks:
      - service-tier
  mysql-content:
    build: ./mysql
    image: oli/mysql
    container_name: oli-mysql-content-service
    env_file:
      - ../content-service/service.envs
    ports:
      - "3377:3307"
    volumes:
      - /oli/databases/content:/var/lib/mysql
#      - content-db:/var/lib/mysql
    networks:
      - service-tier
  keycloak-sso:
    build: ./keycloak-mysql
    image: oli/keycloak-mysql
    container_name: oli-keycloak
    env_file:
      - ./keycloak-mysql/keycloak.envs
#    volumes:
#      - /oli/databases/keycloak_dump:/export
    networks:
      - service-tier
    depends_on:
      - mysql-keycloak
  content:
    build: ../content-service
    image: oli/content-service
    container_name: content-service
    env_file:
      - ../content-service/service.envs
    environment:
      - MYSQL_ADDRESS=mysql-content
    ports:
      - "9110:9990"  # for remote deployment
      - "8787:8787"  # for remote debugging
      - "9990:9990"  # for remote debugging
    volumes:
      - /oli/content/course_content_xml:/oli/course_content_xml
      - /oli/content/webcontent:/oli/webcontent
      - /oli/repository:/oli/repository
      - /oli/dtd:/oli/dtd
    networks:
      - service-tier
    depends_on:
      - mysql-content
  nginx:
    build: frontend-nginx
    image: oli/nginx
    container_name: oli-nginx
    volumes:
      - ../course-editor/dist:/oli/course-editor/dist
    networks:
      - service-tier
  web-assets:
    build: ./web-assets-nginx
    image: oli/web-assets-nginx
    container_name: oli-web-assets-nginx
    volumes:
      - /oli/content/webcontent:/oli/webcontent/webcontents
      - /oli/repository:/oli/repository
      - /oli/superactivity:/oli/superactivity
      - /oli/branding:/oli/branding
    networks:
      - service-tier
  ssh-server:
    build: ./ssh-server
    image: oli/ssh-server
    container_name: oli-ssh-server
    env_file:
      - ./ssh-server/ssh.envs
    networks:
      - service-tier
  dev.local:
    build: ./ha-proxy
    image: oli/haproxy
    container_name: oli-haproxy
    ports:
      - "80:80"
      - "443:443"
      - "2222:2222"
    networks:
      - service-tier
    depends_on:
      - nginx
      - web-assets
      - content
      - ssh-server
networks:
  service-tier:
    driver: bridge
#volumes:
#  content-db:
#  keycloak-db: