version: '3.1'
services:
  mysql-keycloak:
    build: ./mysql
    container_name: oli-mysql-keycloak
    env_file:
      - ./keycloak-mysql/keycloak.envs
    volumes:
      - /oli/databases/keycloak:/var/lib/mysql
#      - keycloak-db:/var/lib/mysql
    networks:
      - service-tier
    depends_on:
      - fluentd
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: "oli.oli-mysql-keycloak"
  mysql-content:
    build: ./mysql
    image: oli/mysql
    container_name: oli-mysql-content-service
    env_file:
      - ../content-service/service.envs
    ports:
      - "3377:3307"
    volumes:
      - /oli/databases/content:/var/lib/mysql
#      - content-db:/var/lib/mysql
    networks:
      - service-tier
    depends_on:
      - fluentd
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: "oli.oli-mysql-content"
  keycloak-sso:
    build: ./keycloak-mysql
    image: oli/keycloak-mgysql
    container_name: oli-keycloak
    env_file:
      - ./keycloak-mysql/keycloak.envs
#    volumes:
#      - /oli/databases/keycloak_dump:/export
    networks:
      - service-tier
    depends_on:
      - mysql-keycloak
      - fluentd
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: "oli.oli-keycloak"
  content:
    build: ../content-service
    image: oli/content-service
    container_name: content-service
    env_file:
      - ../content-service/service.envs
    environment:
      - MYSQL_ADDRESS=mysql-content
    ports:
      - "9110:9990"  # for remote deployment
      - "8787:8787"  # for remote debugging
    volumes:
      - /oli/content/course_content_xml:/oli/course_content_xml
      - /oli/content/webcontent:/oli/webcontent
      - /oli/repository:/oli/repository
      - /oli/dtd:/oli/dtd
    networks:
      - service-tier
    depends_on:
      - mysql-content
      - fluentd
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: "oli.oli-content-service"
  editor:
    build: ../course-editor
    image: oli/editor
    container_name: oli-editor
    ports:
      - "9000:9000"
    networks:
      - service-tier
    volumes:
      - ../course-editor:/app
      - ../course-editor/dist:/app/dist
      - /app/node_modules
    command: npm run dev
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: "oli.oli-editor"
  nginx:
    build: frontend-nginx
    image: oli/nginx
    container_name: oli-nginx
    volumes:
      - ../course-editor/dist:/oli/course-editor/dist
    networks:
      - service-tier
    depends_on:
      - fluentd
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: "oli.oli-nginx"
  web-assets:
    build: ./web-assets-nginx
    image: oli/web-assets-nginx
    container_name: oli-web-assets-nginx
    volumes:
      - /oli/content/webcontent:/oli/webcontent/webcontents
      - /oli/repository:/oli/repository
      - /oli/superactivity:/oli/superactivity
      - /oli/branding:/oli/branding
    networks:
      - service-tier
    depends_on:
      - fluentd
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: "oli.oli-web-assets"
  ssh-server:
    build: ./ssh-server
    image: oli/ssh-server
    container_name: oli-ssh-server
    env_file:
      - ./ssh-server/ssh.envs
    networks:
      - service-tier
    depends_on:
      - fluentd
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: "oli.oli-ssh-server"
#  gateway:
#    build: ../gateway
#    image: oli/gateway
#    container_name: oli-gateway
#    networks:
#      - service-tier
#    depends_on:
#      - fluentd
#    logging:
#      driver: fluentd
#      options:
#        fluentd-address: localhost:24224
#        tag: "oli.oli-gateway"
  dev.local:
    build: ./ha-proxy
    image: oli/haproxy
    container_name: oli-haproxy
    ports:
      - "80:80"
      - "443:443"
      - "2222:2222"
    networks:
      - service-tier
    depends_on:
      - nginx
      - web-assets
#      - gateway
      - content
      - editor
      - ssh-server
      - fluentd
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: "oli.oli-haproxy"
  fluentd:
    build: ./fluentd
    image: oli/fluentd
    container_name: oli-fluentd
    networks:
      - service-tier
  elasticsearch:
    image: elasticsearch
    container_name: oli-elasticsearch
    expose:
      - 9200
    networks:
      - service-tier
  kibana:
    image: kibana
    container_name: oli-kibana
    networks:
      - service-tier
networks:
  service-tier:
    driver: bridge
