version: '3.1'
services:
  mysql-keycloak:
    build: ./mysql
    image: oli/mysql
    container_name: oli-mysql-keycloak
    env_file:
      - ./keycloak-mysql/keycloak.envs
    volumes:
      - /oli/databases/keycloak:/var/lib/mysql
      - /oli/databases/keycloak_conf:/etc/mysql/conf.d
#    ports:
#      - "33206:3306"
    networks:
      - service-tier
  keycloak-sso:
    build: ./keycloak-mysql
    image: oli/keycloak-mysql
    container_name: oli-keycloak
    env_file:
      - ./keycloak-mysql/keycloak.envs
    volumes:
      - /oli/databases/keycloak_dump:/export
    networks:
      - service-tier
    depends_on:
      - mysql-keycloak
  mysql-content:
    build: ./mysql
    image: oli/mysql
    container_name: oli-mysql-content-service
    env_file:
      - ../content-service/service.envs
    volumes:
      - /oli/databases/content:/var/lib/mysql
      - /oli/databases/content_conf:/etc/mysql/conf.d
#    ports:
#      - "33382:3306"
    networks:
      - service-tier
  content:
    build: ../content-service
    image: oli/content-service
    container_name: content-service
    env_file:
      - ../content-service/service.envs
    environment:
      - MYSQL_ADDRESS=mysql-content
    ports:
#      - "8110:8080"
      - "9110:9990"
      - "8787:8787"  # for remote debugging
    volumes:
      - /oli/content/course_content_xml:/oli/course_content_xml
      - /oli/content/course_content_volume:/oli/course_content_volume
      - /oli/content/course_content_out:/oli/course_content_out
      - /oli/content/webcontent:/oli/webcontent
    networks:
      - service-tier
    depends_on:
      - keycloak-sso
      - mysql-content
  editor:
    container_name: oli-editor
    build: ../course-editor
    image: oli/editor
#    ports:
#      - "9000:9000"
    networks:
      - service-tier
    volumes:
      - ../course-editor:/app
      - ../course-editor/dist:/app/dist
      - /app/node_modules
    command: npm run dev
  nginx:
    build: ./nginx
    image: oli/nginx
    container_name: oli-nginx
    volumes:
      - /oli/content/webcontent:/oli/webcontent/webcontents
      - ../course-editor/dist:/oli/course-editor/dist
    networks:
      - service-tier
  ssh-server:
    build: ./ssh-server
    image: oli/ssh
    container_name: oli-ssh
    networks:
      - service-tier
  dev.local:
    build: ./ha-proxy
    image: oli/haproxy
    container_name: oli-haproxy
    ports:
      - "80:80"
      - "443:443"
      - "2222:2222"
    networks:
      - service-tier
    depends_on:
      - content
      - editor
      - ssh-server
networks:
  service-tier:
    driver: bridge
