version: '2.1'
services:
  mysql-keycloak:
    image: mysql
    container_name: oli-mysql-keycloak
    env_file:
      - ./keycloak-mysql/keycloak.envs
    volumes:
      - /oli/databases/keycloak:/var/lib/mysql
    ports:
      - "33206:3306"
    networks:
      - service-tier
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: "oli.oli-mysql-keycloak"
  keycloak-sso:
    build: ./keycloak-mysql
    image: oli/keycloak-mysql
    container_name: oli-keycloak
    env_file:
      - ./keycloak-mysql/keycloak.envs
    networks:
      - service-tier
    depends_on:
      - mysql-keycloak
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: "oli.oli-keycloak"
  mysql-content:
    image: mysql
    container_name: oli-mysql-content-service
    env_file:
      - ./content-service/service.envs
    volumes:
      - /oli/databases/content:/var/lib/mysql
    ports:
      - "33306:3306"
    networks:
      - service-tier
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: "oli.oli-mysql-content-service"
  content:
    build: ./content-service
    image: oli/content-service
    container_name: content-service
    env_file:
      - ./content-service/service.envs
    environment:
      - MYSQL_ADDRESS=mysql-content
    ports:
      - "8110:8080"
      - "9110:9990"
    volumes:
      - /oli/content/course_content_xml:/oli/course_content_xml
      - /oli/content/course_content_volume:/oli/course_content_volume
      - /oli/content/webcontent:/oli/webcontent
    networks:
      - service-tier
    depends_on:
      - keycloak-sso
      - mysql-content
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: "oli.content-service"
  nginx:
    build: ./nginx
    image: oli/nginx
    container_name: oli-nginx
    volumes:
      - /oli/content/webcontent:/oli/webcontent/webcontents
    networks:
      - service-tier
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: "oli.oli-nginx"
  shattrath.oli.cmu.edu:
    build: ./ha-proxy
    image: oli/haproxy
    container_name: oli-haproxy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - service-tier
    depends_on:
      - content
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: "oli.oli-haproxy"
networks:
  service-tier:
    driver: bridge
